import 'package:flutter/material.dart';

class AppColor {
  static const scaffoldColor = Color(0xffFFFFFF);
  static const appBarBackButtonColor = Color(0xDD000000);
  static const showpasswordColor = Color(0xff9e9e9e);
  static const appBarHeadingColor = Color(0xff00bcd4);
  static const pageHeadingColor = Color(0xDD000000);
  static const textFieldInputColor = Color(0xffbdbdbd);
  static const textFieldLabelColor = Color(0xff00bcd4);
  static const appTandCcolor = Color(0xDD000000);
  static const bottomTextColor = Color(0xff00bcd4);
  static const bottonTextColor = Color(0xff000000);
  static const snackbarBackgroundColor = Color(0xff4dd0e1);
  static const bottomsecondColor = Color(0xDD000000);
  static const bottomsecondHighlightColor = Color(0xff26c6da);
  static const appLoginButtons = Color(0xff26c6da);
  static const checkBoxActiveColor = Color(0xff4dd0e1);
  static const emotionTilesBlueColor = Color(0xff2F80ED);
  static const emotionTilesBlueSelectedColor = Color(0xffCAE0FF);
  static const emotionTilesGreenColor = Color(0xff219653);
  static const emotionTilesGreenSelectedColor = Color(0xffdeffec);
  static const emotionTilesRedColor = Color(0xffeb5757);
  static const emotionTilesRedSelectedColor = Color(0xffffDEDE);
  static const emotionTilesYellowColor = Color(0xfff2c94c);
  static const emotionTilesyellowSelectedColor = Color(0xfffffaec);
  static const emotionTilesUnselectedColor = Color(0xffffffff);
  static const circleWidShadowColor1 = Color(0xff2DC4D9);
  static const circleWidShadowColor2 = Color(0xffffffff);
  static const userPostBackground = Color(0xffffffff);
  static const userPostNameColor = Color(0xff000000);
  static const userPostTimeColor = Color(0xff555555);
  static const userPostEmotionColor = Color(0xff27AE60);
  static const userPostIconColor = Color(0xffAAAAAA);
  static const userPostBottomTextColor = Color(0xff595959);
  static const userPostBottomIconColor = Color(0xff2DC4D9);
  static const userStatusBarColor = Color(0xff000000);
  static const onlineIndicator = Color(0xff4caf50);
  static const offlineIndicator = Color(0xff2196f3);
  static const loginChoiceTextColor = Color(0xff2DC4D9);
  static const forgetpassInformationColor = Color(0xff757575);
}
